<tr>
	<td colspan="2" style="padding-top: 0; padding-left: 0;">
		
		<p class="description"><?php echo $desc; ?></p>
		<br />
		<table class="wmcs_currency_table widefat" width="100%">
			<tbody id="wmcs_currencies">
				<?php echo $currency_table_rows; ?>
			</tbody>
			<tfoot>
				<td colspan="2">
					<button class="button-primary" type="button" id="wmcs_settings_add_currency">Add new currency to store</button>
				</td>
			</tfoot>
		</table>

	</td>
</tr>